name: Laravel Pint

on:
  pull_request:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write

jobs:
  pint:
    uses: stefanzweifel/reusable-workflows/.github/workflows/laravel-pint-fixer.yml@main
